print(f"{1 + 2 = }")
print(f"{-1 = }")
print(f"{5 - 3 = }")
print(f"{5 - 3.0 = }")
print(f"{4 * 4 = }")
print(f"{2 ** 8 = }")
print()
print(f"{12 / 3 = }")
print(f"{11 / 3 = }")
print(f"{11 // 3.0 = }")
print(f"{11 % 3 = }")
print()
print(f"{'abc' + 'def' = }")
print(f"{'ABC' * 3 = }")
print()
# приведёт к ошибке
# print(f"{1 + '1'}")
