@startuml


frame nl1 as "  слой 1  " {
    circle n1_1 as "нейрон 1"
    circle n1_2 as "нейрон 2"
    circle n1_3 as "нейрон 3"
}

frame nl2 as "  слой 2  " {
    circle n2_1 as "нейрон 1"
    circle n2_2 as "нейрон 2"
}

    circle n3_1 as "нейрон 3"


n2_1 --[plain]-> n1_1
n2_1 --[plain]-> n1_2
n2_1 --[plain]-> n1_3

n2_2 --[plain]-> n1_1
n2_2 --[plain]-> n1_2
n2_2 --[plain]-> n1_3

n1_1 ---> n3_1
n1_2 ---> n3_1
n1_3 ---> n3_1


@enduml